name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 👈 Pin to stable version

    steps:
    - name: Set up job
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # 👈 Correct and available version

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev git zip unzip openjdk-17-jdk
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK Build Tools 34.0.0
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: aviator-predictor-apk
        path: bin/*.apk
