name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libtool libffi-dev ruby python3-pip python3-setuptools \
            zip unzip openjdk-17-jdk wget git python3-dev build-essential

          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK and Tools
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk.zip
          unzip sdk.zip -d temp
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv temp/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest

          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app-apk
          path: bin/*.apk
