name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer cython

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Set up Android SDK manually
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform

        # Download command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools-temp

        # Move and rename to proper structure
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools-temp/cmdline-tools/* android-sdk/cmdline-tools/latest/

        # Add to PATH
        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        # Accept licenses and install required tools
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=android-sdk \
          "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Build APK
      run: |
        pip install --user buildozer
        buildozer android debug
