name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget
        pip install --upgrade pip
        pip install Cython
        pip install buildozer

    - name: Install Android SDK and AIDL
      env:
        ANDROID_HOME: $HOME/android-sdk
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools/latest
        cd $ANDROID_HOME/cmdline-tools

        # Download and unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdtools.zip
        unzip cmdtools.zip -d temp

        # Move the actual cmdline-tools into the 'latest' folder
        mv temp/cmdline-tools/* latest/

        # Set path to include sdkmanager
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

        # Accept licenses and install required tools
        yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses
        sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;34.0.0" "platforms;android-34"

    - name: Build APK
      env:
        ANDROID_HOME: $HOME/android-sdk
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH
      run: |
        cd aviator-predictor-app  # Change if your actual folder is different
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Aviator Predictor APK
        path: aviator-predictor-app/bin/*.apk
