name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev \
            libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev

      - name: Install buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK licenses and install build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aviator-apk
          path: bin/*.apk
